### ISSUE TITLE
Baseline model implementation

### ISSUE THREAD

**Issue by suibian1213** [MrZQAQ/MCANet#1]
Hello, I was reading your paper about MACNet recently.
According to MCANet you compared MCANet with MolTrans, TransformerCPI etc.

These baseline models are implemented by yourself or their official repositories?Because I have also reproduced these two benchmark methods recently, but found that the AUPR result in your paper is higher than the result written by the original author's paper.And I use the same evaluation metrics as yours in Davis and KIBA, but the result is much worse than yours.

If convenient, could you provide baseline model implementation about Davis and KIBA dataset?

**Comment by MrZQAQ** [comment]
Thanks for your attention!

All baselines are based on official code. The changes include:
- converting the dataset into a format that these baselines can read
- fixing a few deprecated API calls in the code to ensure that the same runtime environment can run these code.

Unfortunately, the code for the baseline is stored on a server and I currently do not have access to that server.
I hope to be able to release the code as soon as possible in the coming months.

**Comment by suibian1213** [comment]
Do you remember what modifications you made to the official repository? For example, whether the data division has been modified, whether cross-validation has been performed, whether hyperparameters have been modified, etc.

**Comment by MrZQAQ** [comment]
> Do you remember what modifications you made to the official repository? For example, whether the data division has been modified, whether cross-validation has been performed, whether hyperparameters have been modified, etc.

Regarding the hyperparameters, I don't remember making any changes to them. The dataset was split with 5 fold cross validation.

**Comment by suibian1213** [comment]
Ok,thanks!Hope you can release the code soon.

**Comment by MrZQAQ** [comment]
I got permission to access the storage again recently, but I found that the data had been deleted.
I found some code in the archive that may not be exactly the same as the code used for the baseline comparison in the paper.
I have posted these codes in [another repository](https://github.com/MrZQAQ/MCANet_Baseline) and hope this will be helpful.

**Comment by suibian1213** [comment]
thank you！
