### ISSUE TITLE
Question about how to preprocess about DeepConv-DTI

### ISSUE THREAD

**Issue by TorchZhan** [MrZQAQ/MCANet#2]
Dear authors:

I want to know how the author trained the baseline about DeepConv-DTI mainly about how to preprocess the origin data, When I trained the code ar DeepConv-DTI, the memory was quiet high. 

Thank you very much for your kind consideration and I am looking forward to your reply.

**Comment by MrZQAQ** [comment]
For questions about DeeoConvDTI, I suggest asking its author. It works fine in my runtime.
The code for data processing, which is stored in [another repository](https://github.com/MrZQAQ/MCANet_Baseline), is usually a script named `convert_dataset.py`
